CREATE TABLE FSS.IPADDRESS_DEPT
(
  ID           NUMBER,
  DEPT_ID      VARCHAR2(20 BYTE),
  DEPT_NAME    VARCHAR2(255 BYTE),
  IP_ALL       VARCHAR2(100 BYTE),
  IP_RANGE1    VARCHAR2(20 BYTE),
  IP_RANGE2    VARCHAR2(20 BYTE),
  CATID        VARCHAR2(100 BYTE),
  CANCEL_FLG   VARCHAR2(1 BYTE),
  CREATE_DATE  DATE                             DEFAULT sysdate,
  UPDATE_DATE  DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE FSS.IPADDRESS_DEPT IS 'ตารางเทียบ IP Address';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.ID IS 'pk';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.DEPT_ID IS 'รหัสสังกัด';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.DEPT_NAME IS 'ชื่อสังกัด';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.IP_ALL IS 'IP ทั้งหมด';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.IP_RANGE1 IS 'IP_ ช่วงที่1';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.IP_RANGE2 IS 'IP_ ช่วงที่2';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.CATID IS 'รหัส CATID';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.CANCEL_FLG IS 'สถานะยกเลิก';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.CREATE_DATE IS 'วันที่สร้างข้อมูล';

COMMENT ON COLUMN FSS.IPADDRESS_DEPT.UPDATE_DATE IS 'วันที่ปรับปรุงข้อมูล';