DROP TABLE FSS.RWA_MAIN CASCADE CONSTRAINTS;

CREATE TABLE FSS.RWA_MAIN
(
  ID               NUMBER,
  EMP_CODE         VARCHAR2(10 BYTE),
  LOGTIME          DATE,
  NODEID           NUMBER(1),
  DEPT_ID          VARCHAR2(20 BYTE),
  LAT_WGS84        NUMBER(18,15),
  LON_WGS84        NUMBER(18,15),
  BROWSER          VARCHAR2(100 BYTE),
  BROWSER_VERSION  VARCHAR2(50 BYTE),
  DEVICE           VARCHAR2(100 BYTE),
  DEVICETYPE       VARCHAR2(100 BYTE),
  ORIENTATION      VARCHAR2(100 BYTE),
  OS               VARCHAR2(100 BYTE),
  OS_VERSION       VARCHAR2(100 BYTE),
  USERAGENT        VARCHAR2(255 BYTE),
  IP_ADDRESS       VARCHAR2(100 BYTE),
  CREATE_DATE      DATE,
  CHECKTYPE        VARCHAR2(1 BYTE),
  KM               VARCHAR2(100 BYTE),
  WIFIIP           VARCHAR2(100 BYTE),
  WIFISUBNET       VARCHAR2(100 BYTE),
  CARRIERIP        VARCHAR2(100 BYTE),
  CARRIERSUBNET    VARCHAR2(100 BYTE),
  PHPIP            VARCHAR2(100 BYTE),
  PROBLEM_CAUSE    VARCHAR2(255 BYTE)
)
TABLESPACE FSS_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN FSS.RWA_MAIN.EMP_CODE IS 'รหัสพนักงาน';

COMMENT ON COLUMN FSS.RWA_MAIN.LOGTIME IS 'วัน/เวลา ที่เข้า/ออก';

COMMENT ON COLUMN FSS.RWA_MAIN.NODEID IS '1 เวลาเข้า
2 เวลาออก';

COMMENT ON COLUMN FSS.RWA_MAIN.DEPT_ID IS 'รหัสสังกัด / สังกัดที่ช่วย';

COMMENT ON COLUMN FSS.RWA_MAIN.LAT_WGS84 IS 'พิกัด lat';

COMMENT ON COLUMN FSS.RWA_MAIN.LON_WGS84 IS 'พิกัด lon';

COMMENT ON COLUMN FSS.RWA_MAIN.BROWSER IS 'ชื่อ browser';

COMMENT ON COLUMN FSS.RWA_MAIN.BROWSER_VERSION IS 'เวอร์ชั่น browser';

COMMENT ON COLUMN FSS.RWA_MAIN.DEVICE IS 'ระบบ';

COMMENT ON COLUMN FSS.RWA_MAIN.DEVICETYPE IS 'ไม่ได้ใช้';

COMMENT ON COLUMN FSS.RWA_MAIN.ORIENTATION IS 'รูปแบบแนวตั้ง แนวนอน';

COMMENT ON COLUMN FSS.RWA_MAIN.OS IS 'ระบบปฏิบัติการ';

COMMENT ON COLUMN FSS.RWA_MAIN.OS_VERSION IS 'เวอร์ชั่น OS';

COMMENT ON COLUMN FSS.RWA_MAIN.USERAGENT IS 'รายละเอียด OS';

COMMENT ON COLUMN FSS.RWA_MAIN.IP_ADDRESS IS 'ไอพี แอดเดรส';

COMMENT ON COLUMN FSS.RWA_MAIN.CREATE_DATE IS 'วันที่ทำรายการ';

COMMENT ON COLUMN FSS.RWA_MAIN.CHECKTYPE IS 'การลงเวลา
0 สำนักงาน
1 ไปช่วยปฏิบัติงาน
2 ไม่มี smartphone /ปัญหาอื่นๆ
3 WFH';

COMMENT ON COLUMN FSS.RWA_MAIN.KM IS 'ระยะทาง';

COMMENT ON COLUMN FSS.RWA_MAIN.WIFIIP IS 'ไม่ได้ใช้';

COMMENT ON COLUMN FSS.RWA_MAIN.WIFISUBNET IS 'ไม่ได้ใช้';

COMMENT ON COLUMN FSS.RWA_MAIN.CARRIERIP IS 'ไม่ได้ใช้';

COMMENT ON COLUMN FSS.RWA_MAIN.CARRIERSUBNET IS 'ไม่ได้ใช้';

COMMENT ON COLUMN FSS.RWA_MAIN.PHPIP IS 'ไอพี แอดเดรส';

COMMENT ON COLUMN FSS.RWA_MAIN.PROBLEM_CAUSE IS 'ปัญหาอื่นๆ';