-- Index สำหรับ FSS.RWA_MAIN_DEV
-- ใช้กับ query: SELECT ... WHERE EMP_CODE = :emp_id AND TRUNC(LOGTIME) = TRUNC(SYSDATE)

-- Index สำหรับดึงข้อมูลลงเวลาตามพนักงาน + วันที่
CREATE INDEX FSS.IDX_RWA_MAIN_DEV_EMP_LOGTIME
ON FSS.RWA_MAIN_DEV (EMP_CODE, LOGTIME)
TABLESPACE FSS_DATA;

-- Index สำหรับ FSS.IPADDRESS_DEPT
-- ใช้กับ query: SELECT IP_RANGE1, IP_RANGE2 WHERE DEPT_ID = :dept_id AND CANCEL_FLG != '1'

CREATE INDEX FSS.IDX_IPADDRESS_DEPT_DEPTID
ON FSS.IPADDRESS_DEPT (DEPT_ID, CANCEL_FLG)
TABLESPACE USERS;
